version: '3.8'

services:
  # O Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-financeiro_db}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - finance-network

  # O App (Backend Node.js + Frontend React buildado)
  app:
    build: .
    restart: always
    ports:
      - "3000:3001"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@db:5432/${POSTGRES_DB:-financeiro_db}
      - JWT_SECRET=${JWT_SECRET:-super_secret_jwt_key_s3m}
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - finance-network

volumes:
  pg_data:

networks:
  finance-network:
    driver: bridge
