version: '3.8'

services:
  # O Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-financeiro_db}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - finance-network

  # O App (Backend Node.js + Frontend React buildado)
  app:
    # Em modo Swarm, n√£o podemos usar 'build'. Usamos a imagem gerada pelo GitHub Actions.
    image: ghcr.io/s3multimidia/sistema_financeiro-2:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3001"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@db:5432/${POSTGRES_DB:-financeiro_db}
      - JWT_SECRET=${JWT_SECRET:-super_secret_jwt_key_s3m}
      - NODE_ENV=production
    networks:
      - finance-network

volumes:
  pg_data:

networks:
  finance-network:
    driver: overlay
    attachable: true
